function Run-Task
{
    param(
        [scriptblock] $block
    )

    & $block

    if($LASTEXITCODE -ne 0)
    {
        exit $LASTEXITCODE
    }
}

if (-not (Test-Path env:APPVEYOR_BUILD_NUMBER)) { $env:APPVEYOR_BUILD_NUMBER = '0' }
$suffix = "build." + $env:APPVEYOR_BUILD_NUMBER
$TOOLS_DIR = Join-Path $PSScriptRoot "tools"
$NUGET_EXE = Join-Path $TOOLS_DIR "nuget.exe"

Run-Task { dotnet build BigHelp.Text.csproj -c Release }

Get-ChildItem ./src/*.pp -Recurse | ForEach-Object { Remove-Item $_ }

$files = (Get-ChildItem -Path . -Filter *.cs -File) 
         # + (Get-ChildItem -Path ./src/LibLog/LogProviders -Filter *.cs -File)

$files | ForEach-Object { 
    $in = (Get-Content $_.FullName).Replace('BigHelp.Text.', '$rootnamespace$.');
    Set-Content ($_.FullName + ".pp") -Value '// <auto-generated/>', '// ReSharper disable CheckNamespace', $in;
}

& $NUGET_EXE pack BigHelp.Text.nuspec -Suffix $suffix -OutputDirectory artifacts